spring:
  application:
    name: mq-transfer-biz-worker
transfer:
  common:
    messageQueueMemoryRatio: 0.6
    messageQueueMemoryRatioForSingle: 0.6
    messageConsumerThreadPoolRatio: 0
    messageProducerThreadPoolRatio: 0
  consumer:
    maxSuspendTimeForConsumer: 20000